version: "3.5"

services:
  mongo:
    image: mongo:4.2.0-rc1
    container_name: ${ENV}_workshop_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - workshop
  react:
    image: node:8.16.0
    container_name: ${ENV}_workshop_node
    ports:
      - "8080:3000"
    volumes:
      - ./:/var/www
      - node_modules:/var/www/node_modules
    working_dir: /var/www
    entrypoint: sh -c "npm i && npm start"
    networks:
      - workshop

volumes:
  node_modules:
  mongo_data:

networks:
  workshop:
    name: ${ENV}_workshop_local