version: "3.5"

services:
  react:
    image: apetani/node-app:1.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${ENV}_workshop_node
    ports:
      - "8080:3000"
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    networks:
      - workshop

networks:
  workshop:
    name: ${ENV}_workshop_local